site_name: UPM-AI-GROBID

nav:
  - Home: 'index.rst'
  - Introduction: 'introduction.rst'
  - License: 'license.rst'
  - Workflow: 'workflow.rst'
  - Execution guide: 'execution.rst'
  - Validation: 'rationale.rst'

theme: readthedocs
