site_name: UPM-AI-GROBID

nav:
  - Home: 'index.md'
  - Introduction: 'introduction.md'
  - License: 'license.md'
  - Workflow: 'workflow.md'
  - Execution guide: 'execution.md'
  - Rationale: 'rationale.md'

theme: readthedocs
